baseURL = ""

# determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
# website title
title = "Goodwillhacking"
# Change the default theme to be use when building the site with Hugo
theme = "FeelIt"
# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true

[menu]
  [[menu.main]]
    identifier = "about"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = "<i class='fa-solid fa-user fa-fw'></i>"
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = "<i class='fa-solid fa-file fa-fw'></i>"
    post = ""
    name = "Posts"
    url = "/posts/"
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = "<i class='fa-solid fa-tag fa-fw'></i>"
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3

  [[menu.main]]
    identifier = "github"
    pre = "<i class='fa-brands fa-github fa-fw'></i>"
    post = ""
    name = ""
    url = "https://github.com/goodwillhacking/website"
    title = "GitHub"
    weight = 6

[author]
  name = "Goodwill Hacking"
  link = ""

[params]
  # FeelIt theme version
  version = "1.0.X"
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  gitRepo = "https://github.com/goodwillhacking/website"
  
  # Home page config
  [params.home]
    # amount of RSS pages
    rss = 10
    [params.home.profile]
      enable = true
      # Profile Name
      name = ""
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "https://s3.amazonaws.com/keybase_processed_uploads/ed0f8c2aabe66a75453b4f588b43b005_360_360.jpg"
      # title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page (HTML format is supported)
      subtitle = "Un thème Hugo simple, élégant et efficace"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # disclaimer (HTML format is supported)
      disclaimer = ""
    [params.home.posts]
      enable = false
      # special amount of posts in each home posts page
      paginate = 8
      # display image-preview
      imagePreview = true
  # About page config
  [params.about]
    # whether to enable profile on about page
    # depends on .Site.Params.home.profile.enable
    enable = true
    # whether to enable param layout
    param = true
    # title for param layout
    paramTitle = "Attributes"
    # general description of your site
    # can be write with markdown style
    description = "Technology enthusiast, pragmatic optimist."
    # description of your status
    [[params.about.status]]
      faIcon = "fa-solid fa-building"
      title = "Company"
      desc = "FeelIt"
    [[params.about.status]]
      faIcon = "fa-solid fa-briefcase fa-fw"
      title = "Occupation"
      desc = "Freelancer"
    [[params.about.status]]
      title = "Location"
      faIcon = "fa-solid fa-map-marker-alt"
      desc = "Earth"
    # description of your parameter
    [[params.about.parameter]]
      language = "UI/UX"
      level = "80"
    [[params.about.parameter]]
      language = "HTML"
      level = "70"
    [[params.about.parameter]]
      language = "Go"
      level = "60"
  # PWA config
  [params.pwa]
    # whether to enable PWA support
    enable = true
    # service-worker version
    version = "0.2"
  [params.social]
    GitHub = "goodwillhacking"
    Linkedin = "xxxx"
    Twitter = "tcpipeep"
    Keybase = "goodwillhacking"
  # Site verification code for Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    # google-site-verification=e2vEQKaV2QKz2WrsFqdZVIynFoRIZyvFAEb9hDWeg1k
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""
  # Site SEO config
  [params.seo]
    # image URL
    image = "/images/Apple-Devices-Preview.webp"
    # thumbnail URL
    thumbnailUrl = "/images/screenshot.png"

  # Analytics config
  [params.analytics]
    enable = false
    # GoatCounter Analytics
    [params.analytics.goatcounter]
      # GoatCounter code
      code = "goodwillhacking"
# <script data-goatcounter="https://goodwillhacking.goatcounter.com/count"
#         async src="//gc.zgo.at/count.js"></script>
  [params.search]
    enable = true
    # type of search engine ("lunr", "algolia")
    type = "algolia"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # max number of results length
    maxResultLength = 10
    # snippet length of the result
    snippetLength = 30
    # HTML tag name of the highlight part in results
    highlightTag = "em"
    # whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false

    [languages.en.params.search.algolia]
      index = "index.en"
      appID = "2VL5EWI1V4"
      searchKey = "3e0af571b39369e23e9464692e529737"

  # Page config
  [params.page]
    # whether to hide a page from home page
    hiddenFromHomePage = false
    # whether to hide a page from search results
    hiddenFromSearch = false
    # whether to enable lightgallery
    lightgallery = false
    # whether to enable the ruby extended syntax
    ruby = true
    # whether to enable the fraction extended syntax
    fraction = true
    # whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to use the fontawesome as cdn source
    cdnfontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    # whether to show link to improve the article
    improveArticle = "https://github.com/khusika/FeelIt/edit/main/exampleSite/content/"
    # whether to show the full text content in RSS
    rssFullText = false
    # Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      # whether to keep the static table of the contents in front of the post
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
    # Code config
    [params.page.code]
      # whether to show the copy button of the code block
      copy = true
      # the maximum number of lines of displayed code by default
      maxShownLines = 10
    # KaTeX mathematical formulas config (KaTeX https://katex.org/)
    [params.page.math]
      enable = false
      # default block delimiter is $$ ... $$ and \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # default inline delimiter is $ ... $ and \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX extension copy_tex
      copyTex = true
      # KaTeX extension mhchem
      mhchem = true
    # Mapbox GL JS config (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
    [params.page.mapbox]
      # access token of Mapbox GL JS
      accessToken = "pk.eyJ1IjoiZ29vZHdpbGxoYWNraW5nIiwiYSI6ImNseGhpcHN5dTE5eTMyaW92NjBvMXh6a2QifQ.S4Jr0s_I0Pq8mTkeaqhy2A"
      # style for the light theme
      lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
      # style for the dark theme
      darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
      # whether to add NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
      navigation = true
      # whether to add GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
      geolocate = true
      # whether to add ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
      scale = true
      # whether to add FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
      fullscreen = true
    # Social share links in post page
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false
      HackerNews = true
      Reddit = false
      RSS = true
    # Comment config
    [params.page.comment]
      enable = true
      [params.page.comment.vssue]
        # https://vssue.js.org/guide/github.html#config-and-start-your-vssue
        enable = true
        # Vssue platform API ("bitbucket", "gitea", "gitee", "github", "github-v4", "gitlab")
        platform = "github"
        owner = "goodwillhacking"
        repo = "website"
        clientId = "Ov23lioMBEjBKBPu6U6g"
        clientSecret = ""

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Permalinks config (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  posts = ":filename"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  term = ["HTML", "RSS"]
  taxonomy = ["HTML"]
