---
name: goodwill-hacking
region: nyc
alerts:
  - rule: DEPLOYMENT_LIVE
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
ingress:
  rules:
    - component:
        name: website
      cors:
        allow_origins:
          - prefix: https://nicholas.karonji.com
      match:
        path:
          prefix: /

static_sites:
  - name: website
    environment_slug: hugo
    github:
      branch: dev
      deploy_on_push: true
      repo: goodwillhacking/website
    envs:
      - key: HUGO_VERSION
        value: "0.127.0"
        scope: BUILD_TIME
        type: GENERAL
      - key: HUGO_EXTENDED
        value: "1"
        scope: BUILD_TIME
        type: GENERAL
    build_command: git submodule add -f https://github.com/khusika/FeelIt.git themes/FeelIt; hugo --config hugo.toml --destination ./public
