---
name: GoodwillHacking
static_sites:
  - build_command: hugo --destination ./public
    environment_slug: hugo
    github:
      branch: main
      deploy_on_push: true
      repo: goodwillhacking/website
    name: GoodwillHacking
